version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: buddybot_postgres
    restart: always
    environment:
      POSTGRES_USER: buddy
      POSTGRES_PASSWORD: password
      POSTGRES_DB: buddybot
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local 